### ISSUE TITLE
RENEE GUI failing

### ISSUE THREAD

**Issue by samarth8392** [CCBR/RENEE#175]
module loaded ccbrpipeliner/7 and launched a job via renee gui. Terminal captured these errors (before dry run). Seems like some permissions issue under /data/CCBR_Pipeliner?
```
Traceback (most recent call last):
  File "/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.2/main.py", line 16, in <module>
    sys.exit(main())
             ^^^^^^
  File "/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.2/src/renee/__main__.py", line 1500, in main
    args.func(args)
  File "/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.2/src/renee/gui.py", line 193, in launch_gui
    allout = exec_in_context(run, run_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/CCBR_Pipeliner/db/PipeDB/Conda/envs/py311/lib/python3.11/site-packages/ccbr_tools/shell.py", line 18, in exec_in_context
    func(*args, **kwargs)
  File "/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.2/src/renee/run.py", line 55, in run
    dryrun_output = dryrun(
                    ^^^^^^^
  File "/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.2/src/renee/dryrun.py", line 55, in dryrun
    raise e
  File "/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.2/src/renee/dryrun.py", line 20, in dryrun
    dryrun_output = subprocess.check_output(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/CCBR_Pipeliner/db/PipeDB/Conda/envs/py311/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/CCBR_Pipeliner/db/PipeDB/Conda/envs/py311/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/CCBR_Pipeliner/db/PipeDB/Conda/envs/py311/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/CCBR_Pipeliner/db/PipeDB/Conda/envs/py311/lib/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'snakemake'
```

**Comment by kopardev** [comment]
@samarth8392  .. can you forcefully run an older version 2.5.x and see if gui works for that?

**Comment by kopardev** [comment]
@samarth8392  ... does the older version still work?

**Comment by samarth8392** [comment]
Apologies for not responding sooner. Just loaded renee v2.5.12 using ccbrpipeliner 6 and GUI launches and dry-run output shows up. No issues. Didn't submit a full run but it should work.

**Comment by samarth8392** [comment]
## update ##

GUI seems to be working now with renee `v2.6.3`. 
I think the issue has been resolved.
See below:

```
renee gui
[+] Loading singularity  4.1.5  on cn4268 
[+] Loading snakemake  7.32.4 
Python version: 3.11.3
RENEE (v2.6.3)
{'hg19_19': '/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.3/config/genomes/biowulf/hg19_19.json', 'mm10_M23': '/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.3/config/genomes/biowulf/mm10_M23.json', 'hg19_36': '/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.3/config/genomes/biowulf/hg19_36.json', 'hg38_30': '/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.3/config/genomes/biowulf/hg38_30.json', 'mmul10_mmul10_108': '/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.3/config/genomes/biowulf/mmul10_mmul10_108.json', 'hg38_36': '/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.3/config/genomes/biowulf/hg38_36.json', 'mm10_M21': '/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.3/config/genomes/biowulf/mm10_M21.json', 'hg38_45': '/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.3/config/genomes/biowulf/hg38_45.json', 'hg38_41': '/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.3/config/genomes/biowulf/hg38_41.json', 'hg38_34': '/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.3/config/genomes/biowulf/hg38_34.json', 'hg38_38': '/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.3/config/genomes/biowulf/hg38_38.json', 'mm10_M25': '/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/RENEE/.v2.6.3/config/genomes/biowulf/mm10_M25.json'}
['hg19_19', 'hg19_36', 'hg38_30', 'hg38_34', 'hg38_36', 'hg38_38', 'hg38_41', 'hg38_45', 'mm10_M21', 'mm10_M23', 'mm10_M25', 'mmul10_mmul10_108']
layout is ready!
/data/CCBR_Pipeliner/db/PipeDB/Conda/envs/py311/lib/python3.11/re/_parser.py:543: ResourceWarning: unclosed <socket.socket fd=4, family=2, type=1, proto=0, laddr=('0.0.0.0', 0)>
  subpatternappend((LITERAL, _ord(this)))
ResourceWarning: Enable tracemalloc to get the object allocation traceback
window created!
--SUBMIT-- {'--INDIR--': '/data/CCBR/projects/techDev/data/rna', 'Browse': '', '--OUTDIR--': '/data/CCBR/projects/techDev/runs/renee_test', 'Browse0': '', '--ANNOTATION--': 'hg38_38'}
['/data/CCBR/projects/techDev/data/rna/sample1.R1.fastq.gz', '/data/CCBR/projects/techDev/data/rna/sample1.R2.fastq.gz', '/data/CCBR/projects/techDev/data/rna/sample2.R1.fastq.gz', '/data/CCBR/projects/techDev/data/rna/sample2.R2.fastq.gz']


```
